### ISSUE TITLE
Only aerial imagery visible for bounds for which data was downloaded.

### ISSUE THREAD

**Issue by PolyglotOpenstreetmap** [michaelzangl/josm-plugin-opengl#1]
Hi Michael,

Great work! Your modified josm plays nice with the Mapillary plugin :-). What is odd, is that aerial imagery is only visible for those areas/bounds where data has been downloaded explicitely. I'm working with a 240MB OSM file downloaded with Overpass API with all ways/relations of PT in Belgium as a skeleton. So I only download extra data where I plan to add another public transport itinerary/line with all its variations. And those are the only places for which there are bounds in the OSM file.
MapCSS behaves as expected (mostly, there are some artefacts at some zoom levels). Filtering works too.

Should I notice a speed difference when zooming in and out?

Polyglot

**Comment by michaelzangl** [comment]
Hi. Thanks for testing.

I know about the download area problem. GLG2D is not able to render that texture correctly, so it simply fills the area hiding your areal image. A workaround is to disable drawing the download areas in the settings dialog.

You might notice that the speed is slower compared to what it is in the default version. This is because there are no optimizations added yet.

**Comment by michaelzangl** [comment]
This should be fixed in the current version.
